### ISSUE TITLE
load overflow scroll issue

### ISSUE THREAD

**Issue by RezaHaidari** [egoist/vue-mugen-scroll#1]
I have a problem with infinite-scroll in "overflow:scroll" section, when i scroll this section to end, just loading will appear but doesn't handle method until page(browser) scrolled.

![issue](https://cloud.githubusercontent.com/assets/12013210/19827650/775c1244-9dbe-11e6-86a2-a535ea54234f.gif)

**Comment by egoist** [comment]
Hi, I've added a new prop for this, check out https://github.com/egoist/vue-mugen-scroll#scrollconatiner

Let me know if there's any issues.

**Comment by RezaHaidari** [comment]
thanks

in SSR(server-side rendering) i give that error:

Uncaught TypeError: Cannot read property 'addEventListener' of undefined

i think in server context, "window" is undefined. should first check if in browser context.

**Comment by egoist** [comment]
eh, I'm not sure if `mounted()` will be called in SSR, and `windows` is only used in that method

**Comment by RezaHaidari** [comment]
thank you so much it works very well @egoist 
sorry I made a mistake, i forgot add ref to my container. I thought class name is for reference, I didn't saw ref attribute in example.

**Comment by egoist** [comment]
Glad to hear that 🍻
