### ISSUE TITLE
how to run this example in local?

### ISSUE THREAD

**Issue by UserHuRu** [egoist/vue-mugen-scroll#5]

**Comment by egoist** [comment]
You can run the example with [vbuild](https://github.com/egoist/vbuild), [I just added it to devDependencies](https://github.com/egoist/vue-mugen-scroll/commit/eb569ad50385af236f9de8da6674e7ca6dcfa06e) so now you can:

```bash
git clone https://github.com/egoist/vue-mugen-scroll.git
cd vue-mugen-scroll
yarn
yarn example
```

**Comment by UserHuRu** [comment]
Thanks very much ~
