### ISSUE TITLE
After handler had completed - mugen-component stays in viewport...

### ISSUE THREAD

**Issue by monochromatique** [egoist/vue-mugen-scroll#7]
and stop firing handler at all, reacting only on scroll and resize events.

My case.

I get 20 chat messages from server for initial. If it takes more space than viewport offer - it's ok, coz I need to scroll. 

But if mugen-compo stays in viewport - nothing happens. It's strange behaviour. The only chance to fire event - resizing browser.

Now I add '**DOMNodeInserted**' to triggers array and it work.

**Comment by egoist** [comment]
Can you provide a repro on jsbin/jsfiddle/codepen btw?

**Comment by egoist** [comment]
I actually feel that `<mugen-scroll />` stays in viewport is the expected behavior, in such case, a `load more` button is the solution for you:

```js
<mugen-scroll :should-handle="!loading" :handler="fetchData">
  <button>{{ loading ? 'Loading' : 'Load More }}</button>
</mugen-scroll>
```
